FROM python:3.12-slim

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./app ./app
CMD ["fastapi", "run", "app/main.py", "--port", "80"]

# docker build -t device-walker:latest .
# docker run \
# --rm \
# --name device-walker \
# -p 80:80 \
# --env-file .env \
# device-walker:latest

