class DeviceWalkerError(Exception): ...


class NetboxDeviceNotFoundError(DeviceWalkerError): ...


class NetboxDeviceAmbError(DeviceWalkerError): ...


class FactoryError(DeviceWalkerError): ...


class CLIAuthenticationError(DeviceWalkerError): ...


class CLITimedOutError(DeviceWalkerError): ...
