class CommandCollectorError(Exception): ...


class NetboxError(CommandCollectorError): ...


class NetboxRequestError(NetboxError): ...


class NetboxDeviceNotFoundError(NetboxError): ...


class NetboxDeviceAmbiguousError(NetboxError): ...


class NetboxDeviceValidationError(NetboxError): ...


class CLIError(CommandCollectorError): ...


class CLITimeoutError(CLIError): ...


class CLIAuthenticationFailed(CLIError): ...
